name: Build

on:
  push:
  pull_request:

jobs:
  sanity_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Check format
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Generate
        run: flutter build apk

      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/app/outputs/flutter-apk/app-release.apk
